version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0

jobs:
  build-api:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Restore NuGet packages
          command: dotnet restore AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Build
          command: dotnet build --configuration Release AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Test
          command: dotnet test --configuration Release AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Publish
          command: dotnet publish --configuration Release --output ./publish AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj 
      - persist_to_workspace:
          root: .
          paths:
            - publish
  
  build-bff:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Restore NuGet packages
          command: dotnet restore AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Build
          command: dotnet build --configuration Release AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Test
          command: dotnet test --configuration Release AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Publish
          command: dotnet publish --configuration Release --output ./publish AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - persist_to_workspace:
          root: .
          paths:
            - publish
              
  build-and-push-image:
    aws-ecr/build-and-push-image:
      context: $CONTEXT
      repo: $ECR_NAME
      tag: latest
      path: $PUBLISH_PATH
      
  build-and-push-api-test:
    environment:
      CONTEXT: appsettingsmanager-api-test
      ECR_NAME: 'appsettingsmanager-test-api'
      PUBLISH_PATH: AppSettingsManagerApi/AppSettingsManagerApi/publish
    steps:
      - build-and-push-image

  build-and-push-api-prod:
    environment:
      CONTEXT: appsettingsmanager-api-prod
      ECR_NAME: 'appsettingsmanager-prod-api'
      PUBLISH_PATH: AppSettingsManagerApi/AppSettingsManagerApi/publish
    steps:
      - build-and-push-image
  
  build-and-push-bff-test:
    environment:
      CONTEXT: appsettingsmanager-bff-test
      ECR_NAME: 'appsettingsmanager-test-bff'
      PUBLISH_PATH: AppSettingsManagerBff/AppSettingsManagerBff/publish
    steps:
      - build-and-push-image

  build-and-push-bff-prod:
    environment:
      CONTEXT: appsettingsmanager-bff-prod
      ECR_NAME: 'appsettingsmanager-prod-bff'
      PUBLISH_PATH: AppSettingsManagerBff/AppSettingsManagerBff/publish
    steps:
      - build-and-push-image
  
workflows:
  version: 2
  build-deploy-api:
    jobs:
      - build-api
      - approval-for-test-api:
          requires: [ build-api ]
          type: approval
      - build-and-push-api-test:
          requires: [ approval-for-test-api ]
      - approval-for-prod-api:
          requires: [ build-and-push-api-test ]
          type: approval
          filters:
            branches:
              only: main
      - build-and-push-api-prod:
          requires: [ approval-for-prod-api ]
          
  build-deploy-bff:
    jobs:
      - build-bff
      - approval-for-test-bff:
          requires: [ build-bff ]
          type: approval
      - build-and-push-bff-test:
          requires: [ approval-for-test-bff ]
      - approval-for-prod-bff:
          requires: [ build-and-push-bff-test ]
          type: approval
          filters:
            branches:
              only: main
      - build-and-push-bff-prod:
          requires: [ approval-for-prod-bff ]
