version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0

jobs:
  build-api:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Restore NuGet packages
          command: dotnet restore AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Build
          command: dotnet build --configuration Release AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Test
          command: dotnet test --configuration Release AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj
      - run:
          name: Publish
          command: dotnet publish --configuration Release --output ./publish AppSettingsManagerAPI/AppSettingsManagerApi/AppSettingsManagerApi.csproj 
      - persist_to_workspace:
          root: .
          paths:
            - publish
  
  build-bff:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Restore NuGet packages
          command: dotnet restore AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Build
          command: dotnet build --configuration Release AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Test
          command: dotnet test --configuration Release AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - run:
          name: Publish
          command: dotnet publish --configuration Release --output ./publish AppSettingsManagerBff/AppSettingsManagerBff/AppSettingsManagerBff.csproj
      - persist_to_workspace:
          root: .
          paths:
            - publish
              
  
workflows:
  version: 2
  build-deploy-api:
    jobs:
      - build-api
      - approval-for-test-api:
          requires: [ build-api ]
          type: approval
      - aws-ecr/build-and-push-image:
          requires: [ approval-for-test-api ]
          context: appsettingsmanager-api-test
          repo: appsettingsmanager-test-api
          tag: latest
          path: AppSettingsManagerAPI/AppSettingsManagerApi/publish
#      - approval-for-prod-api:
#          requires: [ build-and-push-api-test ]
#          type: approval
#          filters:
#            branches:
#              only: main
#      - build-and-push-api-prod:
#          requires: [ approval-for-prod-api ]
          
